image:
    name: docker/compose:latest
services:
    - docker:dind
pre_clone_script:
    - sudo chown -R gitlab-runner:gitlab-runner .
before_script:
    - docker version
    - docker-compose version
build:
    stage: build
    only:
        - main
    script:
        - docker-compose -f docker-compose.yml down --remove-orphan
        - docker-compose -f docker-compose.yml up -d --build
        - docker rmi $(docker images -f dangling=true -q)
