version: '3.3'

services:

  talo-mongo:
    image: mongo
    container_name: talo-mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./talo-mongo:/data/db
    environment:
      MONGO_INITDB_DATABASE: talo
    networks:
      - talo

  talo-redis:
    image: redis
    container_name: talo-redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - talo

  talo-nodejs:
    container_name: talo-nodejs
    restart: on-failure:3
    build: 
      context: ./talo_nodejs
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - DATABASE_URL=mongodb://talo-mongo:27017/talo
      - REDIS_URL=redis://talo-redis:6379
      - JWT_SECRET_KEY=TALO
      - JWT_LIFE_ACCESS_TOKEN=3d
      - JWT_LIFE_REFRESH_TOKEN=60d
      - OTP_EXPIRE_MINUTE=2
      - EMAIL=talo.noreply@gmail.com
      - EMAIL_PASSWORD=
      - TWILIO_ACCOUNT_SID=
      - TWILIO_AUTH_TOKEN=
      - MAX_SIZE_FILE=52428800
      - GOOGLE_CLOUD_PROJECT=talo
      - CLOUD_BUCKET_AVATAR=talo-avatar
      - CLOUD_BUCKET_COVER_PHOTO=talo-cover-photo
      - CLOUD_BUCKET_GROUP_AVATAR=talo-group-avatar
      - CLOUD_BUCKET_GROUP_IMAGE=talo-group-image
      - CLOUD_BUCKET_GROUP_VIDEO=talo-group-video
      - CLOUD_BUCKET_GROUP_FILE=talo-group-file
      - CLOUD_BUCKET_STICKER=talo-sticker
    depends_on:
      - talo-redis
      - talo-mongo
    networks:
      - talo

  talo-reactjs:
    container_name: talo-reactjs
    restart: on-failure:3
    build: 
      context: ./talo_reactjs
      dockerfile: Dockerfile.dev
      args:
        - REACT_APP_API_URL=http://localhost/api
        - REACT_APP_URL=http://localhost
        - REACT_APP_SOCKET_URL=http://localhost
    ports:
      - 3000:3000
    depends_on:
      - talo-nodejs
    networks:
      - talo

  talo-nginx:
    image: nginx
    container_name: talo-nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./talo-nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - talo-nodejs
      - talo-reactjs
    networks:
      - talo

networks:
  talo:
    driver: bridge
volumes:
    talo-mongo: